# This will appear before many messages from the plugin.
message-prefix: '&8[&7Waygates&8]'

# Use a minecraft colour code here to pick the message colour
message-colour: '7'

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '8'
